# ----------------------------
# Makefile Options
# ----------------------------

NAME = ScrnSavr
APP_NAME = ScrnSavr
APP_INST_NAME = SCRNSAVR
APP_VERSION = 5.0.0.0000
APPVAR_VERSION = 0
DESCRIPTION = "(C)  2025  RoccoLox  &  TIny_Hacker"
COMPRESSED = NO
ARCHIVED = YES

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include app_tools/makefile
