# ----------------------------
# Makefile Options
# ----------------------------

NAME = SCRNSAVR
ICON = icon.png
DESCRIPTION = ""
COMPRESSED = YES
COMPRESSED_MODE = zx0

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
